force-app/main/default/objects/Header__c/Header__c.object-meta.xml
<CustomObject>
    <label>Header</label>
    <nameField>
        <label>Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <referenceTo>Header__c</referenceTo>
    <relationshipLabel>Ticket</relationshipLabel>
    <relationshipName>Ticket</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchClassTest.cls
@isTest
public class BatchClassTest {
    
    @isTest
    static void testBatchClass() {
        
        // STEP 1 - Insert Parent Record first
        Header__c parentHeader = new Header__c();
        parentHeader.Name = 'Test Header';  
        // add any required fields of Header__c object here
        insert parentHeader;
        
        // STEP 2 - Assign Parent Id to Ticket
        Ticket__c t = new Ticket__c();
        t.Status__c = 'A';
        t.Country__c = 'India';
        t.Header__c = parentHeader.Id; 
        insert t;
        
    }
}