force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Prior_status__c.field-meta.xml
<CustomField>
    <fullName>Prior_status__c</fullName>
    <label>Prior status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchClass.cls
public class BatchClass implements Database.Batchable<sObject>{
    
    public static Database.QueryLocator start(Database.BatchableContext context){
        
        //   string strquery = 'SELECT Id,Prior_status__c,Name,Country__c, Status__c FROM Ticket__c Where Status__c = 'A'';
        //system.debug('---strquery----'+strquery);
        
        return Database.getQueryLocator([SELECT Id,Prior_status__c,Name,Country__c, Status__c FROM Ticket__c Where Status__c = 'A']);
    }
    public void execute(Database.BatchableContext context, List<Ticket__c> Scope){
        
        list<Ticket__c> lstTicket = new list<Ticket__c>();
        for(Ticket__c Tic : Scope){
            system.debug('----Tic-----'+Tic);
            
            Tic.Prior_status__c = Tic.Status__c;
            Tic.Status__c = 'C';
            lstTicket.add(Tic);
            
            system.debug('----Tic.Status__c-----'+Tic.Status__c);
        }
        update lstTicket;
    }
    public void finish(Database.BatchableContext context){
        
        system.debug('----Finish------');
    }
}